### ISSUE TITLE
Add a "Name" field to IIRCHandler so we can tell which handler causes crashes

### ISSUE THREAD

**Issue by xforever1313** [xforever1313/Chaskis#64]
It is hard to debug why exceptions appear in the StringParsingThread.  We should add a property to IIrcHandler that is the "Name" or "Context".  Then, when we get an exception, we can dump that to the log.

This should be an optional property set on the Config objects.  If null, use some default name in the handler itself.

**Comment by xforever1313** [comment]
So we didn't go with the "Name" option.  Rather, when a exception gets thrown on the StringParsingQueue, we instead print the stack trace of where the handler was created that caused the exception was thrown.

Error message will look like:

```
2021-01-03T16:06:38.9307750-05:00	chaskis_error>	***************
2021-01-03T16:06:38.9309146-05:00	chaskis_error>	Caught Exception in StringParsingQueue Thread: Executor:
2021-01-03T16:06:38.9311333-05:00	chaskis_error>	An event handler in chaskistests threw a(n) Exception on this message from the server ':nonadminuser!nonadminuser@localhost PRIVMSG #chaskistest :!chaskistest throw My Exception': My Exception
2021-01-03T16:06:38.9312850-05:00	chaskis_error>	Inner Exception was thrown at:
2021-01-03T16:06:38.9313759-05:00	chaskis_error>	   at Chaskis.RegressionTests.RegressionTestPlugin.HandleExceptionThrow(MessageHandlerArgs args) in C:\Users\xfore.000\Documents\Source\Chaskis\Chaskis\RegressionTests\RegressionTestPlugin\RegressionTestPlugin.cs:line 292
2021-01-03T16:06:38.9314265-05:00	chaskis_error>	   at Chaskis.Core.MessageHandler.HandleEvent(HandlerArgs args)
2021-01-03T16:06:38.9314732-05:00	chaskis_error>	   at Chaskis.Core.StringParsingQueue.<>c__DisplayClass9_2.<ParseAndRunEvent>b__0()
2021-01-03T16:06:38.9315235-05:00	chaskis_error>	Event handler that threw this exception was created at: 
2021-01-03T16:06:38.9315694-05:00	chaskis_error>	   at Chaskis.RegressionTests.RegressionTestPlugin.Init(PluginInitor pluginInit) in C:\Users\xfore.000\Documents\Source\Chaskis\Chaskis\RegressionTests\RegressionTestPlugin\RegressionTestPlugin.cs:line 199
2021-01-03T16:06:38.9316157-05:00	chaskis_error>	   at Chaskis.Cli.PluginManager.LoadPlugins(IList`1 assemblyList, IList`1 existingPlugins, IReadOnlyIrcConfig ircConfig, IChaskisEventScheduler scheduler, IInterPluginEventSender eventSender, HttpClient httpClient, String chaskisConfigRoot)
2021-01-03T16:06:38.9316626-05:00	chaskis_error>	   at Chaskis.Cli.Chaskis.InitStage2_LoadPlugins(IList`1 pluginList)
2021-01-03T16:06:38.9317447-05:00	chaskis_error>	   at Chaskis.Cli.Chaskis.InitStage2_LoadPlugins()
2021-01-03T16:06:38.9318070-05:00	chaskis_error>	   at Chaskis.Cli.ChaskisMain.RunChaskis(IReadOnlyList`1 args, CancellationToken cancelToken)
2021-01-03T16:06:38.9318541-05:00	chaskis_error>	   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
2021-01-03T16:06:38.9319000-05:00	chaskis_error>	   at Chaskis.Cli.ChaskisMain.RunChaskis(IReadOnlyList`1 args, CancellationToken cancelToken)
2021-01-03T16:06:38.9319452-05:00	chaskis_error>	   at Chaskis.Cli.MainClass.Main(String[] args)
2021-01-03T16:06:38.9319899-05:00	chaskis_error>	***************
```

**Comment by xforever1313** [comment]
Going to close out this issue.  I think this output should be a lot better now.  At the very least, we can reduce some variables.
